# Generated by Django 4.0.4 on 2022-06-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=8)),
                ('price_on_sale', models.CharField(max_length=8)),
            ],
        ),
    ]
